msgbox"今天是坐在你旁边的林睿的生日,"
msgbox"让我们为ta庆祝吧!"
msgbox"中文版歌曲,GO!"
msgbox"祝ta生日快乐"
msgbox"祝ta生日快乐"
msgbox"祝ta生日快乐"
msgbox"祝ta生日快乐"
msgbox"英文版歌曲,GO!"
msgbox"Happy birthday to ta"
msgbox"Happy birthday to ta"
msgbox"Happy birthday to ta"
msgbox"Happy birthday to ta"
msgbox"party开始啦!"